### ISSUE TITLE
Don't use #-sign to transform to command

### ISSUE THREAD

**Issue by jims** [jschmidt42/stingray-vscode-debugger#9]
This will make the valid lua syntax `#table` work properly. Also there is no need to send the console msg as a `{type: "command"}` message since that is only there for compatibility with old tools. All commands are translated to lua code and executed in the lua vm in the engine. So `perfhud artist` becomes `Console.perfhud("artist")`. Maybe we could use lua comments instead if we want to do this translation automatically? `--perfhud artist`

Great work on this plugin!

**Comment by jschmidt42** [comment]
That's a good idea Jim. I'll make sure to fix this in the next version. `--` sounds like a good idea, or we could add a vscode command extension, so the user can do `F1`, select `Stingray Command`, then type-in the command to be sent to the connected engine. What do you think?

**Comment by jims** [comment]
Maybe command extension actually, then we could parse the list of available commands from the engine. In the debug console you can manually write `Console.perfhud(...)` etc anyway :D

**Comment by jschmidt42** [comment]
Fixed in v1.2 (https://github.com/jschmidt42/stingray-vscode-debugger/tree/v1.2)
![image](https://cloud.githubusercontent.com/assets/4054655/24785031/86f28a4c-1b24-11e7-8454-95fc190692ef.png)

I also added a `Stingray Command` using the command palette:

![image](https://cloud.githubusercontent.com/assets/4054655/24785041/99d2ea62-1b24-11e7-901a-b29786464da6.png)

![image](https://cloud.githubusercontent.com/assets/4054655/24785046/a58557b4-1b24-11e7-8b1c-20a48cd38952.png)

**Comment by jschmidt42** [comment]
@lochrist FYI
